#! /usr/bin/env python

import pet

engine = pet.engine(True)

con = engine.connect()

con.execute("""insert into package (name, repository_id,id) values ('pkg-with-rc-bug',1,4567);""")
con.execute("""insert into named_tree (id,package_id,type,commit_id,source,version,homepage,last_changed_by,last_changed) values (4567,4567,'branch','ausdausdhasudausdhausdu','pkg-with-rc-bug','1.44-4','https://google.com','{test <test@email.com>}','2016-05-22 11:00:05');""")
con.execute("""insert into bug (id,bug_tracker_id,bug_number,done,severity,tags,subject,submitter,created,owner,forwarded,blocks,blocked_by,last_modified) values (4567,1,4567,'f','serious','{upstream}','bug example','submitter<email@email.com>', '2016-05-21 11:00:05', '','https://test','{}','{}','2016-05-22 11:00:05');""")
con.execute("""insert into bug_source (bug_id,source,fixed_versions,found_versions) values (4567,'pkg-with-rc-bug','{}','{}');""")
#con.execute("""insert into named_tree (id,package_id,type,commit_id) values (4568,3226,'branch','ausdausdhasudausdhausdu');""")

con.close()
