#! /usr/bin/env python
# vim:ts=2:sw=2:et:ai:sts=2
#
# Copyright 2011, Ansgar Burchardt <ansgar@debian.org>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

import pet.models
import pet.update
import pet.ci_debian_packages

import sys


def main(argv):
    number_of_updates = pet.ci_debian_packages.update_ci_status()
    print "%s number(s) of status of packates was updated" % number_of_updates

    session = pet.models.Session()
    for archive_name in argv[1:]:
        archives = session.query(pet.models.Archive).filter_by(
            name=archive_name) \
            .all()
        for archive in archives:
            print "I: Updating archive {0}".format(archive.name)
            updater = pet.update.ArchiveUpdater(archive)
            updater.run()
    session.commit()

if __name__ == '__main__':
    main(sys.argv)
